POST http://localhost:3000/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"test1@mail.com",
    "phone":"081231231",
    "password":"password123"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"test1@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InNhYnJpbmEiLCJwaG9uZSI6IjA4MTIzMTIzMSIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJpYXQiOjE2ODYyMjUzMDB9.PJ5Ry8fX3bldH_TP5Gi_FwhPYYhnVep1INaKpSLbAeA